"""
caproj.visualizations
~~~~~~~~~~~~~~~~~~~~~

This module contains functions for visualizing data and model results

FUNCTIONS

    save_plot()
        Save a matplotlib plot to file

    plot_barplot()
        Generate a horizontal barplot from a pandas value_counts series
"""

import matplotlib.pyplot as plt


def save_plot(plt_object, savepath=None):
    """Save a matplotlib plot to file

    :param plt_object: matplotlib.pyplot plot object
    :param savepath: string or None, specifies filepath at which to save the
                     matplotlib plot. If None, nothing is saved. (Default is
                     None)
    :return: No objects are returned
    """
    if savepath:
        plt_object.savefig(savepath)
    else:
        pass


def plot_barplot(value_counts, title, height=6, varname=None,
                 color='k', label_space=0.01, savepath=None):
    """Generate a horizontal barplot from a pandas value_counts series

    :param value_counts: pd.Series object generated by pandas value_counts()
                         method
    :param title: string, the printed title of the plot
    :param height: integer, the desired height of the plot (default is 6)
    :param color: string, the matplotlib color name for the color you would
                  like for the plotted bars (default is 'k' or black)
    :param label_space: float, a coefficient used to space the count label
                        an appropriate distance from the plotted bar
                        (default is 0.01)
    :param savepath: string or none, specifies filepath at which to save the
                     resulting barplot. If None, nothing is saved. (Default
                     is None)
    :return: a matplotlib plot is generated; no objects are returned
    """
    fig, ax = plt.subplots(figsize=(12, height))

    max_y = max(value_counts.values)
    n_cats = len(value_counts)

    ax.barh(
        range(n_cats), value_counts.values,
        color=color, alpha=1
    )

    [
        ax.text(
            y+max_y*label_space, x,
            '{:,}'.format(y),
            color='k',
            fontsize=12,
            verticalalignment='center'
        )
        for x, y
        in enumerate(value_counts)
    ]

    plt.title(title, fontsize=18)
    plt.yticks(range(n_cats), value_counts.index, fontsize=12)
    plt.xlabel('count', fontsize=14)
    if varname:
        plt.ylabel(varname, fontsize=14)

    plt.grid(':', alpha=0.5)
    plt.tight_layout()

    save_plot(plt_object=plt, savepath=savepath)

    plt.show()
