"""
caproj.data.clean
~~~~~~~~~~~~~~~~~

This module contains BaseData mixin class to clean the NYC Capital Projects dataset

**Module classes:**

.. autosummary::

   CleanMixin

**Module variables:**

.. autosummary::

   log

|
"""
import json
import logging
import math
import os

import pandas as pd

from caproj.logger import logfunc

log = logging.getLogger(__name__)
"""``logging.getLogger`` instance for module"""


class CleanMixin(object):
    """``BaseData`` mixin class methods for cleansing the NYC capital projects dataset
    """

    @logfunc(log=log, funcname=True, docdescr=True, argvals=True, runtime=False)
    def remove_missing_records(self, columns):
        """Delete records with missing values in specified columns

        :param columns: column name(s) for columns to check for blank values, any
                        record with a blank value in the columns will be dropped
                        from dataframe
        :type columns: str or list of str
        """
        columns = list(columns) if type(columns) != list else columns
        self.df.dropna(subset=columns, axis=0, inplace=True)

    @logfunc(log=log, funcname=True, docdescr=True, argvals=True, runtime=False)
    def make_ids(self, columns, id_name="unique_id"):
        """Add new column of id values generated by concatenating other column's values
        """
        columns = list(columns) if type(columns) != list else columns

        class ZeroObject(object):
            def __add__(self, other):
                return other

        self.df[id_name] = sum(
            [self.df[col].map(str) for col in columns], ZeroObject(),
        ).values
