"""
caproj.data.clean
~~~~~~~~~~~~~~~~~

This module contains BaseData mixin class to clean the NYC Capital Projects dataset

**Module classes:**

.. autosummary::

   CleanMixin

**Module variables:**

.. autosummary::

   log

|
"""
import json
import logging
import math
import os

import pandas as pd

from caproj.logger import logfunc

log = logging.getLogger(__name__)
"""``logging.getLogger`` instance for module"""


class CleanMixin(object):
    """``BaseData`` mixin class methods for cleansing the NYC capital projects dataset
    """

    def _concat_values(self, columns):
        """"""
        columns = list(columns) if type(columns) != list else columns

        class ZeroObject(object):
            def __add__(self, other):
                return other

        series_concat = sum(
            [self.df[col].map(str) for col in columns], ZeroObject(),
        ).values

        return series_concat

    @logfunc(log=log, funcname=True, docdescr=True, argvals=True, runtime=False)
    def remove_missing_records(self, columns):
        """Delete records with missing values in specified columns

        :param columns: column name(s) for columns to check for blank values, any
                        record with a blank value in the columns will be dropped
                        from dataframe
        :type columns: str or list of str
        """
        columns = list(columns) if type(columns) != list else columns
        self.df.dropna(subset=columns, axis=0, inplace=True)

    @logfunc(log=log, funcname=True, docdescr=True, argvals=True, runtime=False)
    def concat_values(self, columns, to_colname):
        """Add new column of values generated by concatenating other column's values

        .. todo::
           * Add option to set desired length for each column's values
           * Add option to add seperator between values

        :param columns: name(s) of column(s) for which values should be concatenated
        :type columns: str or list of str
        :param to_colname: name of resulting column containing the concatenated values
        :type to_colname: str
        """
        self.df[to_colname] = self._concat_values(columns=columns)

    def check_duplicates(self, columns):
        """Check column or combination of columns for duplicate records

        .. todo::
            * use pandas duplicated method with keep=False to identify dupe rows
            * log # of duplicated rows and indices of duplicated values
            * use value_counts to identify how many dupes per value > 1 occurance
        """
        raise NotImplementedError
